### ISSUE TITLE
Export and new action issue

### ISSUE THREAD

**Issue by valr13** [WandiParis/EasyAdminPlusBundle#11]
Hi there,

I've an issue when I want to disable the "new" action on a particular entity and when the export action is enable. Both actions disapears of the back-office instead of keeping the export action displayed.

```YAML
# app/config/packages/easy_admin.yaml

easy_admin:
    site_name: 'Easy admin"'
    entities:
        # List the entity class name you want to manage
        User:
            class: App\Entity\User
            disabled_actions: ['new']
            export:

    ...
```

Cheers Wandi :+1:
