### ISSUE TITLE
Generator breaks the default translation domain

### ISSUE THREAD

**Issue by laurent-bientz** [WandiParis/EasyAdminPlusBundle#21]
@kasou 

The generator write this default setting in the EasyAdmin config
```yaml
# config/packages/easy_admin/design.yaml
easy_admin:
    translation_domain: EasyAdminPlusBundle
```
This setting break some translations In EasyAdmin base.

So just remove this generation in `GeneratorGenerate`:
```php
$generatorTool->initTranslation($this->parameters['translation_domain'], $this->projectDir, $locale);
```

thx
